language: cpp

install:
  - sudo apt-get update -qq
  - sudo apt-get install ocaml zlib1g-dev libgc-dev haxe -qq

script:
  - make
  - sudo make install
  - neko -version
  - make test
  - cd test/bin
  - rm RunTests.n
  - haxe RunTests.hxml
  - nekoc RunTests.neko
  - neko RunTests.n
  - cd ../..
