version: "{build}"

environment:
  VisualStudioVersion: 10.0

platform: Win32
configuration: Release

install:
  - cinst make -y
  - cinst 7zip.commandline -y

build_script:
  - set PATH=%PATH%;%APPVEYOR_BUILD_FOLDER%/bin
  - msbuild neko_vc10.sln /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - msbuild libs/libs_vc10.sln /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - copy /y libs\include\gc\gc.dll bin
  - cd %APPVEYOR_BUILD_FOLDER%/src
  - neko ../boot/nekoc tools/install.neko
  - neko tools/install -nolibs
  - cd %APPVEYOR_BUILD_FOLDER%/bin
  - nekoc release.neko
  - neko release.n
  - cd %APPVEYOR_BUILD_FOLDER%

test_script:
  - neko -version
  - cd test
  - appveyor DownloadFile http://haxe.org/download/file/3.2.0/haxe-3.2.0-win.zip
  - 7z x haxe-3.2.0-win.zip -y
  - haxe-3.2.0\haxe.exe RunTests.hxml
  - cd bin
  - rm RunTests.n
  - nekoc RunTests.neko
  - neko RunTests.n
  - cd ../..

artifacts:
  - path: bin/neko-*.zip
